name: Sync with upstream

on:
  schedule:
    - cron: '0 * * * *' # run every hour
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: $ { { secrets.GITHUB_TOKEN }}
          owner: Harry-zklcdc
          repo: go-proxy-bingai
          upstream_branch: main
          target_branch: main
