name: Sync fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨12点运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # 避免使用默认token

    - name: Pull changes
      uses: wei/pull@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用个人token
        UPSTREAM_REPO: Harry-zklcdc/go-proxy-bingai # B库的地址
        UPSTREAM_BRANCH: master # B库的分支
        FORK_BRANCH: master # A库的分支
